/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d8e3fb",
        "outline": "#74777e",
        "on-surface-variant": "#43474d",
        "surface-tint": "#49607e",
        "on-secondary-container": "#72081b",
        "outline-variant": "#c4c6ce",
        "on-error-container": "#93000a",
        "surface-container": "#e7eeff",
        "on-secondary-fixed-variant": "#881c29",
        "on-primary": "#ffffff",
        "on-primary-container": "#7a92b2",
        "secondary-container": "#ff757c",
        "secondary": "#a9343f",
        "primary-fixed": "#d2e4ff",
        "inverse-surface": "#263143",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-primary-fixed-variant": "#314865",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#cfdaf2",
        "primary-container": "#102a45",
        "inverse-on-surface": "#ecf1ff",
        "background": "#f9f9ff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001c37",
        "surface-container-low": "#f0f3ff",
        "tertiary": "#1d1200",
        "on-secondary-fixed": "#40000a",
        "surface-variant": "#d8e3fb",
        "primary": "#00152b",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#261a00",
        "secondary-fixed": "#ffdad9",
        "inverse-primary": "#b0c8eb",
        "surface-bright": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "on-surface": "#111c2d",
        "on-tertiary-container": "#b28a2a",
        "tertiary-fixed-dim": "#eec05b",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b0c8eb",
        "on-background": "#111c2d",
        "tertiary-container": "#362600",
        "surface": "#f9f9ff",
        "surface-container-high": "#dee8ff",
        "tertiary-fixed": "#ffdea0",
        "secondary-fixed-dim": "#ffb3b3"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin": "3rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "margin-mobile": "1rem",
        "space-xl": "2.5rem"
      },
      fontFamily: {
        "headline-md": [ "Merriweather", "serif" ],
        "body-xl": [ "Inter", "sans-serif" ],
        "label-md": [ "Inter", "sans-serif" ],
        "headline-xl-mobile": [ "Merriweather", "serif" ],
        "label-sm": [ "Inter", "sans-serif" ],
        "body-sm": [ "Inter", "sans-serif" ],
        "headline-xl": [ "Merriweather", "serif" ],
        "headline-lg": [ "Merriweather", "serif" ],
        "display-lg-mobile": [ "Merriweather", "serif" ],
        "display-lg": [ "Merriweather", "serif" ],
        "body-lg": [ "Inter", "sans-serif" ],
        "label-lg": [ "Inter", "sans-serif" ],
        "body-md": [ "Inter", "sans-serif" ],
        "headline-sm": [ "Merriweather", "serif" ]
      },
      fontSize: {
        "headline-md": [ "22px", { "lineHeight": "30px", "fontWeight": "700" } ],
        "body-xl": [ "18px", { "lineHeight": "28px", "fontWeight": "400" } ],
        "label-md": [ "12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" } ],
        "headline-xl-mobile": [ "26px", { "lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700" } ],
        "label-sm": [ "11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "700" } ],
        "body-sm": [ "12px", { "lineHeight": "18px", "fontWeight": "400" } ],
        "headline-xl": [ "36px", { "lineHeight": "44px", "letterSpacing": "-0.015em", "fontWeight": "700" } ],
        "headline-lg": [ "28px", { "lineHeight": "36px", "fontWeight": "700" } ],
        "display-lg-mobile": [ "32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" } ],
        "display-lg": [ "48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" } ],
        "body-lg": [ "16px", { "lineHeight": "24px", "fontWeight": "400" } ],
        "label-lg": [ "14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" } ],
        "body-md": [ "14px", { "lineHeight": "22px", "fontWeight": "400" } ],
        "headline-sm": [ "18px", { "lineHeight": "26px", "fontWeight": "700" } ]
      }
    },
  },
  plugins: [],
};